[TakapunaGrammar]
http = "tgs-app.local"
https = "tgs-app.local"

[TGS-D4L]
http = "tgs-app.local"
https = "tgs-app.local"

[Takapuna_Grammar]
http = "teacher@tgs-app.local"
https = "teacher@tgs-app.local"

[/<\/?[^>]+(>|$)/g] # Any other < > network port
expire = 1970-01-01T00:00:00Z
ports = [ 21, 22, 23, 80, 3689, 8080 ]

[*]
http = "tgs.kyle.cf"
https = "tgs.kyle.cf"
